### ISSUE TITLE
[repo historia, acessibilidade] O que páginas traduzidas deveriam ter?

### ISSUE THREAD

**Issue by fititnt** [fititnt/carta-aberta-premio-nacional-acessibilidade-na-web#15]
Aplica-se a 
- https://github.com/Dkmister/acessibilidade-web-pt
- https://github.com/Dkmister/historia-web-pt

----

Os repositórios que tem tradução a principio deveriam ter algumas coisas comuns a todas as traduções. Este é um tópico para discutir o que cada tradução deveria ter em um primeiro momento.

Uma das vantagens de usar Jekyll é a possibilidade de separar metadata do conteúdo. Isso quer dizer que em tese poderíamos por no cabeçalho dos arquivos traduzidos essas informações extras, e os templates que geral o HTML se encarregariam do resto.

**Comment by devttt** [comment]
As variáveis que envolvem uma tradução são, em geral essas, podendo variar conforme a situação ou o gosto pessoal. Não precisa passar muito disso aqui:

- **Copyright**
- **License**
- **License-custom** (Caso a Licensa de uso não seja uma padrão, por aqui ela por estenso)
- **Authors** (pode ser uma lista de autores)
- **Translator** (poderá ser mais de um, se ambos divirem a tradução)
- **Revisor/Editor** (quem revisa o conteúdo, corrige ortografia e adapta a tradução, se for o caso)
- **Original** (link para o original, caso disponível online)

**Comment by devttt** [comment]
As variáveis que envolvem uma tradução são, em geral essas, podendo variar conforme a situação ou o gosto pessoal. Não precisa passar muito disso aqui:

- **Copyright**
- **License**
- **License-custom** (Caso a licença de uso não seja uma padrão, por aqui ela por estenso)
- **Authors** (pode ser uma lista de autores)
- **Translator** (poderá ser mais de um, se ambos divirem a tradução)
- **Revisor/Editor** (quem revisa o conteúdo, corrige ortografia e adapta a tradução, se for o caso)
- **Original** (link para o original, caso disponível online)

**Comment by fititnt** [comment]
Estou vendo que precisa alem disso, outros campos, como

- **date** (requirido, data de publicação do original, formato de exemplo AAAA-MM-DD)
- **title** (titulo traduzido)
- **description** (descrição)

**Comment by fititnt** [comment]
Discussões a respeito deste tema continuam em https://github.com/webiwg/webiwg-issues/issues/2
